# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.



paginate: 2
paginate_path: "blog/page:num"

port: 4000

# Author settings
author:
  name      : Cao Yang
  job       : Frontend Engineer
  #thumb     : /images/author.jpg
  email     : answershuto@126.com
  github    : http://github.com/answershuto